prometheusOperator:
  createCustomResource: true  # Ensures CRDs are managed by Helm
  createCrd: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 1

grafana:
  enabled: true
  adminPassword: "YourPassword"

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
