alertmanager:
  enabled: true

prometheusOperator:
  createCustomResource: true  # Helm manages CRDs
  createCrd: true  # Ensure CRDs are created

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

grafana:
  enabled: true
  adminPassword: "YourPassword"

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

coreDns:
  enabled: true

kubeProxy:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true
