prometheus:
  enabled: true
  nodeExporter:
    enabled: false
  kubeProxy:
    enabled: false
  coreDns:
    enabled: false

grafana:
  enabled: true

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true
